name: Terraform Apply

on:
  workflow_dispatch:

# on:
#     push:
#         branches:
#             - aws-secretsmanager


jobs:
    terraformapply:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "./terraform/"
        environment: aws
        permissions:
          security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Download terraform.tfvars from S3 Bucket
              run: |
                aws s3 cp s3://terraform-state-ecs-project-charlie/terraform.tfvars .

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.11.1

            - name: Terraform Init
              run: terraform init

            - name: Terraform Apply
              run: terraform apply -auto-approve