name: Terraform Apply

# on:
#   workflow_dispatch:

on:
    push:
        branches:
            - aws-secretsmanager


jobs:
    terraformapply:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: "./terraform/"
        environment: aws
        permissions:
          security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Download terraform.tfvars from S3 Bucket
              run: |
                aws s3 cp s3://terraform-state-ecs-project-charlie/terraform.tfvars terraform.tfvars

            - name: Checkout
              uses: actions/checkout@v4
  
            - name: Setup Tflint
              uses: terraform-linters/setup-tflint@master
              with: 
                tflint_version: latest
  
            - name: TFlint Scan   #See this link for command flags https://github.com/terraform-linters/tflint and https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/config.md#format
              run: |
                touch tflint-results-terraform.sarif
                tflint --recursive --color
              continue-on-error: true
        
            - name: Checkov
              uses: bridgecrewio/checkov-action@master
              with:
                framework: terraform
                soft_fail: true   #Soft fail true means that the pipeline will stil continue to run regardless if a vulnerability was detected. Soft fail false would be the opposite where a detected vulnerability will cause the pipeline to stop running
                output_format: cli,sarif
                output_file_path: checkov-results-terraform.sarif
                
            - name: Upload Checkov scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              if: success() || failure()
              with:
                  sarif_file: 'checkov-results-terraform.sarif'
                  wait-for-processing: true

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.11.1

            - name: Terraform Init
              run: terraform init

            - name: Terraform Apply
              run: terraform plan
#              run: terraform apply -auto-approve